name: srm check
on:
  push:
    branches: [ 6-Production, main, 1-SamShoberWork-PersonalBranch, 2-Feature-Branch, 4-Dev, 5-Testing, 3-Release-Branch ]
  pull_request:
    branches: [ 6-Production, main, 1-SamShoberWork-PersonalBranch ] ## , 2-Feature-Branch, 4-Dev, 5-Testing, 3-Release-Branch  ]
  workflow_dispatch:
jobs:
  test-compose-action:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      checks: write
      contents: write
      deployments: write
      id-token: write
      issues: write
      discussions: write
      packages: write
      repository-projects: write
      security-events: write
      statuses: write

    env:
      SEEKER_SERVER_URL: ${{ vars.SEEKER_SERVER_URL }}
      SEEKER_PROJECT_KEY: ${{ vars.SEEKER_PROJECT_KEY }}
      SEEKER_SCAN_REQUIRED: ${{vars.SEEKER_SCAN_REQUIRED }}
      SRM_BreakBuild_Policy: any
      
    steps:
        - name: Get SRM Project ID
          id: get_srm_project_id
          run: |
            SRM_Project_ID=$(curl -s -X 'POST' \
            'https://testing.srm.synopsys.com/srm/api/projects/query' \
              -H 'accept: */*' \
              -H "API-Key: ${{ secrets.SRM_APIKEY }}" \
              -H 'Content-Type: */*' \
              -d '{
              "filter": {
                "name": "${{ github.event.repository.name }}" 
                }
            }' | jq -r '.[0].id')
            echo "SRM_Project_ID=$SRM_Project_ID" >> $GITHUB_ENV
            echo $SRM_Project_ID

        - name: SRM Compliance Check
          run: |
            COMPLIANCE=$(curl -s -X 'GET' \
            'https://testing.srm.synopsys.com/srm/x/projects/${{ env.SRM_Project_ID }};branch=${{ github.ref_name }}/policies/${{ env.SRM_BreakBuild_Policy }}/build-broken' \
              -H 'accept: application/json' \
              -H "API-Key: ${{ secrets.SRM_APIKEY }}")
            if [ "$COMPLIANCE" = "false" ]; then
              echo "SRM Compliance Check Passed"
            else
              if [ "$SRM_COMPLIANCE_FAIL_BUILD" = "true" ]; then
                echo "::error ::SRM compliance check failed." && exit 1
              else
                echo "::warning ::SRM compliance check failed."
              fi
            fi
